### PR TITLE
Check if localeSelector exists before using it

### LINKED ISSUE #94: JS error related to locale when the app has a single locale available
With a single locale in the store, I get this console error:
```
locale_selector.source.js:3 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at locale_selector.source.js:3
```

Adding another locale to `available_locales` of the current store makes the error disappear.

### PR DESCRIPTION
**Pull request by blocknotes**
When the application has a single locale set the locale selector element
is not present.

Closes #94 

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kennyadsl — COMMENTED** [review]
Why also removing all the `;`?

**Comment by blocknotes** [comment]
> Why also removing all the `;`?

Uhm, I'm used to removing them (it will be handled by the JS processor, as the arrow function or any ES6 code).

Do you think it's better to keep them to maintain the same appearance of the other JS or I can leave it as is?

**Comment by kennyadsl** [comment]
I'd like to be consistent and I'm in favor of the refactor if it makes sense, but I think it should be done in a specific task, unrelated to this PR, after a discussion with the team.

**Comment by blocknotes** [comment]
> I'd like to be consistent and I'm in favor of the refactor if it makes sense, but I think it should be done in a specific task, unrelated to this PR, after a discussion with the team.

I fixed up the last commit to restoring the `;`

**Review by kennyadsl — APPROVED** [review]
Thanks!

**Pull request merged**
