### PR TITLE
Copy missing solidus_support_extensions during the installation

### LINKED ISSUE #137: `solidus_auth_devise` does not work with installation via copy
`solidus_auth_devise` currently requires `SolidusSupport.frontend_available?` to return `true` in order to load its frontend routes, controllers and views. 
This method is originally [defined](https://github.com/solidusio/solidus_support/blob/66074b4a2e6339a7f4e7fce7de242ec46e1aa28b/lib/solidus_support.rb#L49) in `solidus_support` but it has been [patched](https://github.com/nebulab/solidus_starter_frontend/blob/master/lib/solidus_starter_frontend/solidus_support_extensions.rb)  in this extension but the patch is not copied during the `copy` installation process. 

When no practical solution can be found, I think we should at least document this in the readme.

### PR DESCRIPTION
**Pull request by blocknotes**
Closes #137.

## Description
- Copy _solidus_support_extensions.rb_ during the installation
- Prepare an initializer to load it in the target application

## How Has This Been Tested?
- Prepared a new Solidus app
- Executed the install procedure
- Checked in console `SolidusSupport.frontend_available?`

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by blocknotes** [comment]
@spaghetticode had a problem with this PR - error info:
```
~/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require’: cannot load such file -- solidus_support (LoadError)
```
Disabling the new initializer cleans the error.

More investigation needed 🤔

**Comment by vibhoo** [comment]
When this PR will be merged ?

**Comment by blocknotes** [comment]
Thank you for your interest @vibhoo.
About this one, we are waiting for feedback about the effective resolution of the source issue.
ATM I haven't more information to share about it.

**Review by spaghetticode — APPROVED** [review]
@blocknotes thank you 👍

**Pull request merged**
